// src/components/Hand.svelte
<script lang="ts">
    import Card from './Card.svelte';
    import type { Card as CardType } from '../types';

    export let cards: CardType[] = [];
    export let showTotal: boolean = true;
    export let total: number = 0;
</script>

<div class="hand">
    <div class="cards">
        {#each cards as card}
            <Card suit={card.suit} rank={card.rank} faceDown={card.faceDown || false} />
        {/each}
    </div>

    {#if showTotal}
        <div class="total">Total: {total}</div>
    {/if}
</div>

<style>
    .hand {
        position: relative;
    }

    .cards {
        display: flex;
        justify-content: center;
        gap: 1vw;
        margin-bottom: 0.5vh;
        flex-wrap: wrap;
    }

    .total {
        position: absolute;
        bottom: 0.5vh;
        right: 1.5vw;
        font-size: clamp(1rem, 2.2vh, 1.5rem);
        font-weight: bold;
        color: white;
        text-shadow: 1px 1px 3px rgba(0,0,0,0.8);
    }
</style>

// src/components/Hand.tsx
import type { Card as CardType } from '../types';
import Card from './Card';
import './Hand.css';

interface HandProps {
    cards?: CardType[];
    showTotal?: boolean;
    total?: number;
}

export default function Hand({ cards = [], showTotal = true, total = 0 }: HandProps) {
    return (
        <div className="hand">
            <div className="cards">
                {cards.map((card, index) => (
                    <Card key={`${card.suit}-${card.rank}-${index}`} suit={card.suit} rank={card.rank} faceDown={card.faceDown || false} />
                ))}
            </div>

            {showTotal && <div className="total">Total: {total}</div>}
        </div>
    );
}
